---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: cron
      cronjob: "25 4 1,14 * *"
      timezone: "Europe/Helsinki"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "02:00"
