[tool.poetry]
name = "herrfors-scraper"
version = "0.1.0"
description = ""
authors = ["Sebastian Lövdahl <slovdahl@hibox.fi>"]
readme = "README.md"
packages = [{include = "herrfors_scraper"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
