[tool.poetry]
name = "herrfors-scraper"
version = "0.1.0"
description = ""
authors = ["Sebastian Lövdahl <slovdahl@hibox.fi>"]
readme = "README.md"
license = "MIT"
packages = [
    { include = "herrfors_scraper" },
]

[tool.poetry.dependencies]
python = "^3.8"
python-dateutil = "2.8.1"
influxdb = "5.3.0"
requests = "2.31.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.282"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-auto-export]
output = "requirements.txt"
without_hashes = true
without = ["dev"]

[tool.ruff]
line-length = 88  # defaults to 88 like black
target-version = "py38"

select = [
    "ALL"
]

ignore = [
    "D203",    # one-blank-line-before-class
    "D213",    # multi-line-summary-second-line
    "PLR2004", # magic-value-comparison
]

unfixable = [
    "ARG001",  # Unused function argument
    "F841",    # Local variable name is assigned to but never used
]

[tool.ruff.isort]
known-first-party = ["herrfors_scraper"]
